### ISSUE TITLE
Align Search page's header to homepage

### ISSUE THREAD

**Issue by notthetup** [org-arl/unet-blog#9]
_From @sayanee on September 3, 2018 12:50_

![image](https://user-images.githubusercontent.com/413879/44987664-89793500-afba-11e8-80c0-219cb62997de.png)

# Todo

- [ ] Amend the header image to the same as the homepage
- [ ] Amend the heading size to the same as the homepage
- [ ] Amend the subtitle size to the same as the homepage

_Copied from original issue: notthetup/unet-blog#3_

**Comment by AnneThKu** [comment]
Search page modified. Please check if it is fine.

<img width="1430" alt="search page" src="https://user-images.githubusercontent.com/42397354/45584984-74cc6380-b90f-11e8-9d11-f7e50b4b9202.png">

**Comment by AnneThKu** [comment]
will add the particles same as home page.

**Comment by AnneThKu** [comment]
Added the particles also in the image.

<img width="1432" alt="search_page_2" src="https://user-images.githubusercontent.com/42397354/45585081-2324d880-b911-11e8-8440-fc771d636264.png">

**Comment by notthetup** [comment]
Fixed in ec68b7f
